name: Build and Deploy to GKE

on:
  push:
    branches:
    # - brian
    - crawler
    # - yuchen
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: autopilot-cluster-1    # TODO: update to cluster name
  GKE_ZONE: asia-east1   # TODO: update to cluster zone
  DEPLOYMENT_NAME: crawler-dpm # TODO: update to deployment name
  CRAWLER_IMAGE: crawler-image
  URL_MANAGER_IMAGE: url-manager-image
  FLASK_SERVER_IMAGE: flask-server-image

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Setup gcloud CLI
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'
    - uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GKE_PROJECT }}

    # Configure Docker to use the gcloud command-line tool as a credential
    # helper for authentication
    - run: |-
        gcloud --quiet auth configure-docker
    # Get the GKE credentials so we can deploy to the cluster
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
    
    # Build the Docker image
    - name: BuildCrawler
      run: |-
        cd ./Crawler
        docker build \
          --tag "gcr.io/$PROJECT_ID/$CRAWLER_IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    
    
    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        docker push "gcr.io/$PROJECT_ID/$CRAWLER_IMAGE:$GITHUB_SHA"
    # - name: Publish
    #   run: |-
    #     docker push "gcr.io/$PROJECT_ID/$URL_MANAGER_IMAGE:$GITHUB_SHA"

    # Set up kustomize
    - name: Set up Kustomize
      run: |-
        cd ./Crawler/k8s # 如果 mainfest 是放在某一個資料夾，這邊要替換成該資料夾名稱
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        cd ./Crawler/k8s # 如果 mainfest 是放在某一個資料夾，這邊要替換成該資料夾名稱
        ./kustomize edit set image gcr.io/PROJECT_ID/CRAWLER_IMAGE:TAG=gcr.io/$PROJECT_ID/$CRAWLER_IMAGE:$GITHUB_SHA
        ./kustomize build . | kubectl apply -f -
        kubectl rollout status deployment/$DEPLOYMENT_NAME
        kubectl get services -o wide
